version: '2'

# Maintainer: facugon
# this is used for development

services:
  theeye-redis:
    image: redis:latest
    container_name: theeye-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
       - /srv/docker/redis:/data
    networks:
      - theeye

  theeye-mongodb:
    image: mongo:4.2
    container_name: theeye-mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /srv/docker/mongodb:/data/db
      - ./mongodump:/data/dump
    networks:
      - theeye   

  theeye-ldap:
    image: rroemhild/test-openldap
    container_name: theeye-ldap
    restart: always
    ports:
      - "389:389"
      - "636:636"
      - "10389:10389"
      - "10636:10636"
    networks:
      - theeye

  theeye-mailserver:
    image: djfarrelly/maildev
    container_name: theeye-mailserver
    restart: always
    ports:
      - "6083:80"
      - "6025:25"
    networks:
      - theeye

  theeye-nginx:
    #image: nginx
    image: imkulikov/nginx-sticky
    container_name: theeye-nginx
    restart: always
    volumes: 
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "8080:80"
    networks:
      - theeye

networks:
   theeye:
      external:
         name: theeye
